// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcsxxtzxmsjjgdqsgofw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jc3h4dHp4bXNqamdkcXNnb2Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0ODE0NDIsImV4cCI6MjA3NDA1NzQ0Mn0.3-eFFEWNXcKpapF2VLTndUUn5W6zshdWi7r4YBqkAGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});